backend:
  name: git-gateway
  branch: main # Rama de tu repositorio
media_folder: "src/content/docs/assets" # Carpeta para imágenes
collections:
  - name: docs
    label: Documentation
    folder: "src/content/docs"
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: description, label: Description, widget: string }
      - { name: body, label: Body, widget: markdown }